// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auwvgimsiynkfmzdbpug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1d3ZnaW1zaXlua2ZtemRicHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTc0MTcsImV4cCI6MjA1MjU5MzQxN30.96rR-XKKmtaKZ3QoRT_YxNmIAGg2cwyJiXCDafpEOcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);